// CommonMark inputs for the conformance test, one per section of the specification, written for this
// repository. The specification's own example file is CC-BY-SA, which ADR-0006 forbids in this tree,
// so the suite instead drives the reference implementation (commonmark, BSD-2-Clause) as the oracle:
// for each input, our AST rendered to HTML must equal what the reference implementation produces.

export interface SpecCase {
  /** The section of the CommonMark specification this input exercises. */
  readonly section: string;
  readonly input: string;
}

export const COMMONMARK_CASES: readonly SpecCase[] = [
  // 2 Preliminaries
  { section: 'tabs', input: '\tfoo\tbaz\t\tbim\n' },
  { section: 'tabs', input: '  \tfoo\tbaz\t\tbim\n' },
  { section: 'tabs', input: '- foo\n\n\t\tbar\n' },
  { section: 'tabs', input: '>\t\tfoo\n' },
  { section: 'tabs', input: '#\tFoo\n' },
  { section: 'insecure characters', input: 'a\u0000b\n' },
  { section: 'blank lines', input: '  \n\naaa\n  \n\n# aaa\n\n  \n' },

  // 4.1 Thematic breaks
  { section: 'thematic breaks', input: '***\n---\n___\n' },
  { section: 'thematic breaks', input: '+++\n===\n' },
  { section: 'thematic breaks', input: '--\n**\n__\n' },
  { section: 'thematic breaks', input: ' ***\n  ***\n   ***\n' },
  { section: 'thematic breaks', input: '    ***\n' },
  { section: 'thematic breaks', input: 'Foo\n    ***\n' },
  { section: 'thematic breaks', input: '_____________________________________\n' },
  { section: 'thematic breaks', input: ' - - -\n' },
  { section: 'thematic breaks', input: ' **  * ** * ** * **\n' },
  { section: 'thematic breaks', input: '_ _ _ _ a\n\na------\n\n---a---\n' },
  { section: 'thematic breaks', input: ' *-*\n' },
  { section: 'thematic breaks', input: '- foo\n***\n- bar\n' },
  { section: 'thematic breaks', input: 'Foo\n***\nbar\n' },
  { section: 'thematic breaks', input: 'Foo\n---\nbar\n' },
  { section: 'thematic breaks', input: '* Foo\n* * *\n* Bar\n' },
  { section: 'thematic breaks', input: '- Foo\n- * * *\n' },

  // 4.2 ATX headings
  { section: 'atx headings', input: '# foo\n## foo\n### foo\n#### foo\n##### foo\n###### foo\n' },
  { section: 'atx headings', input: '####### foo\n' },
  { section: 'atx headings', input: '#5 bolt\n\n#hashtag\n' },
  { section: 'atx headings', input: '\\## foo\n' },
  { section: 'atx headings', input: '# foo *bar* \\*baz\\*\n' },
  { section: 'atx headings', input: '#                  foo                     \n' },
  { section: 'atx headings', input: ' ### foo\n  ## foo\n   # foo\n' },
  { section: 'atx headings', input: '    # foo\n' },
  { section: 'atx headings', input: 'foo\n    # bar\n' },
  { section: 'atx headings', input: '## foo ##\n  ###   bar    ###\n' },
  { section: 'atx headings', input: '# foo ##################################\n##### foo ##\n' },
  { section: 'atx headings', input: '### foo ###     \n' },
  { section: 'atx headings', input: '### foo ### b\n' },
  { section: 'atx headings', input: '# foo#\n' },
  { section: 'atx headings', input: '### foo \\###\n## foo #\\##\n# foo \\#\n' },
  { section: 'atx headings', input: '****\n## foo\n****\n' },
  { section: 'atx headings', input: 'Foo bar\n# baz\nBar foo\n' },
  { section: 'atx headings', input: '## \n#\n### ###\n' },

  // 4.3 Setext headings
  { section: 'setext headings', input: 'Foo *bar*\n=========\n\nFoo *bar*\n---------\n' },
  { section: 'setext headings', input: 'Foo *bar\nbaz*\n====\n' },
  { section: 'setext headings', input: '  Foo *bar\nbaz*\t\n====\n' },
  { section: 'setext headings', input: 'Foo\n-------------------------\n\nFoo\n=\n' },
  { section: 'setext headings', input: '   Foo\n---\n\n  Foo\n-----\n\n  Foo\n  ===\n' },
  { section: 'setext headings', input: '    Foo\n    ---\n\n    Foo\n---\n' },
  { section: 'setext headings', input: 'Foo\n   ----      \n' },
  { section: 'setext headings', input: 'Foo\n    ---\n' },
  { section: 'setext headings', input: 'Foo\n= =\n\nFoo\n--- -\n' },
  { section: 'setext headings', input: 'Foo  \n-----\n' },
  { section: 'setext headings', input: 'Foo\\\n----\n' },
  { section: 'setext headings', input: '`Foo\n----\n`\n\n<a title="a lot\n---\nof dashes"/>\n' },
  { section: 'setext headings', input: '> Foo\n---\n' },
  { section: 'setext headings', input: '> foo\nbar\n===\n' },
  { section: 'setext headings', input: '- Foo\n---\n' },
  { section: 'setext headings', input: 'Foo\nBar\n---\n' },
  { section: 'setext headings', input: '---\nFoo\n---\nBar\n---\nBaz\n' },
  { section: 'setext headings', input: '\n====\n' },
  { section: 'setext headings', input: '---\n---\n' },
  { section: 'setext headings', input: '- foo\n-----\n' },
  { section: 'setext headings', input: '    foo\n---\n' },
  { section: 'setext headings', input: '> foo\n-----\n' },
  { section: 'setext headings', input: '\\> foo\n------\n' },

  // 4.4 Indented code blocks
  { section: 'indented code', input: '    a simple\n      indented code block\n' },
  { section: 'indented code', input: '  - foo\n\n    bar\n' },
  { section: 'indented code', input: '1.  foo\n\n    - bar\n' },
  { section: 'indented code', input: '    <a/>\n    *hi*\n\n    - one\n' },
  { section: 'indented code', input: '    chunk1\n\n    chunk2\n  \n \n \n    chunk3\n' },
  { section: 'indented code', input: '    chunk1\n      \n      chunk2\n' },
  { section: 'indented code', input: 'Foo\n    bar\n\n' },
  { section: 'indented code', input: '    foo\nbar\n' },
  { section: 'indented code', input: '# Heading\n    foo\nHeading\n------\n    foo\n----\n' },
  { section: 'indented code', input: '        foo\n    bar\n' },
  { section: 'indented code', input: '\n    \n    foo\n    \n\n' },
  { section: 'indented code', input: '    foo  \n' },

  // 4.5 Fenced code blocks
  { section: 'fenced code', input: '```\n<\n >\n```\n' },
  { section: 'fenced code', input: '~~~\n<\n >\n~~~\n' },
  { section: 'fenced code', input: '``\nfoo\n``\n' },
  { section: 'fenced code', input: '```\naaa\n~~~\n```\n' },
  { section: 'fenced code', input: '~~~\naaa\n```\n~~~\n' },
  { section: 'fenced code', input: '````\naaa\n```\n``````\n' },
  { section: 'fenced code', input: '```\n' },
  { section: 'fenced code', input: '`````\n\n```\naaa\n' },
  { section: 'fenced code', input: '> ```\n> aaa\n\nbbb\n' },
  { section: 'fenced code', input: '```\n\n  \n```\n' },
  { section: 'fenced code', input: '```\n```\n' },
  { section: 'fenced code', input: ' ```\n aaa\naaa\n```\n' },
  { section: 'fenced code', input: '  ```\naaa\n  aaa\naaa\n  ```\n' },
  { section: 'fenced code', input: '   ```\n   aaa\n    aaa\n  aaa\n   ```\n' },
  { section: 'fenced code', input: '    ```\n    aaa\n    ```\n' },
  { section: 'fenced code', input: '```\naaa\n  ```\n' },
  { section: 'fenced code', input: '```\naaa\n    ```\n' },
  { section: 'fenced code', input: '``` ```\naaa\n' },
  { section: 'fenced code', input: '~~~~~~\naaa\n~~~ ~~\n' },
  { section: 'fenced code', input: 'foo\n```\nbar\n```\nbaz\n' },
  { section: 'fenced code', input: 'foo\n---\n~~~\nbar\n~~~\n# baz\n' },
  { section: 'fenced code', input: '```ruby\ndef foo(x)\n  return 3\nend\n```\n' },
  { section: 'fenced code', input: '~~~~    ruby startline=3 $%@#$\ndef foo(x)\n  return 3\nend\n~~~~~~~\n' },
  { section: 'fenced code', input: '````;\n````\n' },
  { section: 'fenced code', input: '``` aa ```\nfoo\n' },
  { section: 'fenced code', input: '~~~ aa ``` ~~~\nfoo\n~~~\n' },
  { section: 'fenced code', input: '```\n``` aaa\n```\n' },

  // 4.6 HTML blocks
  { section: 'html blocks', input: '<table><tr><td>\n<pre>\n**Hello**,\n\n_world_.\n</pre>\n</td></tr></table>\n' },
  { section: 'html blocks', input: '<table>\n  <tr>\n    <td>\n           hi\n    </td>\n  </tr>\n</table>\n\nokay.\n' },
  { section: 'html blocks', input: ' <div>\n  *hello*\n         <foo><a>\n' },
  { section: 'html blocks', input: '</div>\n*foo*\n' },
  { section: 'html blocks', input: '<DIV CLASS="foo">\n\n*Markdown*\n\n</DIV>\n' },
  { section: 'html blocks', input: '<div id="foo"\n  class="bar">\n</div>\n' },
  { section: 'html blocks', input: '<div></div>\n``` c\nint x = 33;\n```\n' },
  { section: 'html blocks', input: '<Warning>\n*bar*\n</Warning>\n' },
  { section: 'html blocks', input: '<del>\n*foo*\n</del>\n' },
  { section: 'html blocks', input: '<del>\n\n*foo*\n\n</del>\n' },
  { section: 'html blocks', input: '<del>*foo*</del>\n' },
  { section: 'html blocks', input: '<pre language="haskell"><code>\nimport Text.HTML.TagSoup\n\nmain :: IO ()\n</code></pre>\nokay\n' },
  { section: 'html blocks', input: '<script type="text/javascript">\n// JavaScript example\n</script>\nokay\n' },
  { section: 'html blocks', input: '<!-- Foo\n\nbar\n   baz -->\nokay\n' },
  { section: 'html blocks', input: '<?php\n\n  echo ">";\n\n?>\nokay\n' },
  { section: 'html blocks', input: '<!DOCTYPE html>\n' },
  { section: 'html blocks', input: '<![CDATA[\nfunction matchwo(a,b)\n]]>\nokay\n' },
  { section: 'html blocks', input: '  <!-- foo -->\n\n    <!-- foo -->\n' },
  { section: 'html blocks', input: 'Foo\n<div>\nbar\n</div>\n' },
  { section: 'html blocks', input: '<div>\nbar\n</div>\n*foo*\n' },
  { section: 'html blocks', input: 'Foo\n<a href="bar">\nbaz\n' },
  { section: 'html blocks', input: '<div>\n\n*Emphasized* text.\n\n</div>\n' },
  { section: 'html blocks', input: '<table><tr><td>\nhi\n</td></tr></table>\n' },

  // 4.7 Link reference definitions
  { section: 'definitions', input: '[foo]: /url "title"\n\n[foo]\n' },
  { section: 'definitions', input: '   [foo]: \n      /url  \n           \'the title\'  \n\n[foo]\n' },
  { section: 'definitions', input: '[Foo*bar\\]]:my_(url) \'title (with parens)\'\n\n[Foo*bar\\]]\n' },
  { section: 'definitions', input: '[foo]: /url\n\n[foo]\n' },
  { section: 'definitions', input: '[foo]:\n\n[foo]\n' },
  { section: 'definitions', input: '[foo]: <>\n\n[foo]\n' },
  { section: 'definitions', input: '[foo]: /url\n"title" ok\n' },
  { section: 'definitions', input: '    [foo]: /url "title"\n\n[foo]\n' },
  { section: 'definitions', input: '```\n[foo]: /url\n```\n\n[foo]\n' },
  { section: 'definitions', input: 'Foo\n[bar]: /baz\n\n[bar]\n' },
  { section: 'definitions', input: '# [Foo]\n[foo]: /url\n> bar\n' },
  { section: 'definitions', input: '[foo]: /url\nbar\n===\n[foo]\n' },
  { section: 'definitions', input: '[foo]: /url1\n\n[foo]: /url2\n\n[bar][foo]\n' },
  { section: 'definitions', input: '[\nfoo\n]: /url\nbar\n' },
  { section: 'definitions', input: '[foo]: /url\n' },

  // 5.1 Block quotes
  { section: 'block quotes', input: '> # Foo\n> bar\n> baz\n' },
  { section: 'block quotes', input: '># Foo\n>bar\n> baz\n' },
  { section: 'block quotes', input: '   > # Foo\n   > bar\n > baz\n' },
  { section: 'block quotes', input: '    > # Foo\n' },
  { section: 'block quotes', input: '> # Foo\n> bar\nbaz\n' },
  { section: 'block quotes', input: '> bar\nbaz\n> foo\n' },
  { section: 'block quotes', input: '> foo\n---\n' },
  { section: 'block quotes', input: '> - foo\n- bar\n' },
  { section: 'block quotes', input: '>     foo\n    bar\n' },
  { section: 'block quotes', input: '> ```\nfoo\n```\n' },
  { section: 'block quotes', input: '> foo\n    - bar\n' },
  { section: 'block quotes', input: '>\n' },
  { section: 'block quotes', input: '>\n>  \n> \n' },
  { section: 'block quotes', input: '>\n> foo\n>  \n' },
  { section: 'block quotes', input: '> foo\n\n> bar\n' },
  { section: 'block quotes', input: '> foo\n> bar\n' },
  { section: 'block quotes', input: '> foo\n>\n> bar\n' },
  { section: 'block quotes', input: 'foo\n> bar\n' },
  { section: 'block quotes', input: '> aaa\n***\n> bbb\n' },
  { section: 'block quotes', input: '> bar\nbaz\n' },
  { section: 'block quotes', input: '> > > foo\nbar\n' },
  { section: 'block quotes', input: '>>> foo\n> bar\n>>baz\n' },
  { section: 'block quotes', input: '>     code\n\n>    not code\n' },

  // 5.2 List items
  { section: 'list items', input: 'A paragraph\nwith two lines.\n\n    indented code\n\n> A block quote.\n' },
  { section: 'list items', input: '1.  A paragraph\n    with two lines.\n\n        indented code\n\n    > A block quote.\n' },
  { section: 'list items', input: '- one\n\n two\n' },
  { section: 'list items', input: '- one\n\n  two\n' },
  { section: 'list items', input: ' -    one\n\n     two\n' },
  { section: 'list items', input: ' -    one\n\n      two\n' },
  { section: 'list items', input: '   > > 1.  one\n>>\n>>     two\n' },
  { section: 'list items', input: '>>- one\n>>\n  >  > two\n' },
  { section: 'list items', input: '-one\n\n2.two\n' },
  { section: 'list items', input: '- foo\n\n\n  bar\n' },
  { section: 'list items', input: '1.  foo\n\n    ```\n    bar\n    ```\n\n    baz\n\n    > bam\n' },
  { section: 'list items', input: '- Foo\n\n      bar\n\n\n      baz\n' },
  { section: 'list items', input: '123456789. ok\n' },
  { section: 'list items', input: '1234567890. not ok\n' },
  { section: 'list items', input: '0. ok\n\n003. ok\n' },
  { section: 'list items', input: '-1. not ok\n' },
  { section: 'list items', input: '- foo\n\n      bar\n' },
  { section: 'list items', input: '  10.  foo\n\n           bar\n' },
  { section: 'list items', input: '    indented code\n\nparagraph\n\n    more code\n' },
  { section: 'list items', input: '1.     indented code\n\n   paragraph\n\n       more code\n' },
  { section: 'list items', input: '1.      indented code\n\n   paragraph\n\n       more code\n' },
  { section: 'list items', input: '   foo\n\nbar\n' },
  { section: 'list items', input: '-    foo\n\n  bar\n' },
  { section: 'list items', input: '-  foo\n\n   bar\n' },
  { section: 'list items', input: '-\n  foo\n-\n  ```\n  bar\n  ```\n-\n      baz\n' },
  { section: 'list items', input: '-   \n  foo\n' },
  { section: 'list items', input: '-\n\n  foo\n' },
  { section: 'list items', input: '- foo\n-\n- bar\n' },
  { section: 'list items', input: '- foo\n-   \n- bar\n' },
  { section: 'list items', input: '1. foo\n2.\n3. bar\n' },
  { section: 'list items', input: '*\n' },
  { section: 'list items', input: 'foo\n*\n\nfoo\n1.\n' },
  { section: 'list items', input: ' 1.  A paragraph\n     with two lines.\n\n         indented code\n\n     > A block quote.\n' },
  { section: 'list items', input: '  1.  A paragraph\n      with two lines.\n' },
  { section: 'list items', input: '   1.  A paragraph\n       with two lines.\n' },
  { section: 'list items', input: '    1.  A paragraph\n        with two lines.\n' },
  { section: 'list items', input: '  1.  A paragraph\nwith two lines.\n' },
  { section: 'list items', input: '> 1. > Blockquote\ncontinued here.\n' },
  { section: 'list items', input: '- foo\n  - bar\n    - baz\n      - boo\n' },
  { section: 'list items', input: '- foo\n - bar\n  - baz\n   - boo\n' },
  { section: 'list items', input: '10) foo\n    - bar\n' },
  { section: 'list items', input: '10) foo\n   - bar\n' },
  { section: 'list items', input: '- - foo\n' },
  { section: 'list items', input: '1. - 2. foo\n' },
  { section: 'list items', input: '- # Foo\n- Bar\n  ---\n  baz\n' },

  // 5.3 Lists
  { section: 'lists', input: '- foo\n- bar\n+ baz\n' },
  { section: 'lists', input: '1. foo\n2. bar\n3) baz\n' },
  { section: 'lists', input: 'Foo\n- bar\n- baz\n' },
  { section: 'lists', input: 'The number of windows in my house is\n14.  The number of doors is 6.\n' },
  { section: 'lists', input: 'The number of windows in my house is\n1.  The number of doors is 6.\n' },
  { section: 'lists', input: '- foo\n\n- bar\n\n\n- baz\n' },
  { section: 'lists', input: '- foo\n  - bar\n    - baz\n\n\n      bim\n' },
  { section: 'lists', input: '- foo\n- bar\n\n<!-- -->\n\n- baz\n- bim\n' },
  { section: 'lists', input: '-   foo\n\n    notcode\n\n-   foo\n\n<!-- -->\n\n    code\n' },
  { section: 'lists', input: '- a\n - b\n  - c\n   - d\n  - e\n - f\n- g\n' },
  { section: 'lists', input: '1. a\n\n  2. b\n\n   3. c\n' },
  { section: 'lists', input: '- a\n - b\n  - c\n   - d\n    - e\n' },
  { section: 'lists', input: '1. a\n\n  2. b\n\n    3. c\n' },
  { section: 'lists', input: '- a\n- b\n\n- c\n' },
  { section: 'lists', input: '* a\n*\n\n* c\n' },
  { section: 'lists', input: '- a\n- b\n\n  c\n- d\n' },
  { section: 'lists', input: '- a\n- b\n\n  [ref]: /url\n- d\n' },
  { section: 'lists', input: '- a\n- ```\n  b\n\n\n  ```\n- c\n' },
  { section: 'lists', input: '- a\n  - b\n\n    c\n- d\n' },
  { section: 'lists', input: '* a\n  > b\n  >\n* c\n' },
  { section: 'lists', input: '- a\n  > b\n  ```\n  c\n  ```\n- d\n' },
  { section: 'lists', input: '- a\n' },
  { section: 'lists', input: '- a\n  - b\n' },
  { section: 'lists', input: '1. ```\n   foo\n   ```\n\n   bar\n' },
  { section: 'lists', input: '* foo\n  * bar\n\n  baz\n' },
  { section: 'lists', input: '- a\n  - b\n  - c\n\n- d\n  - e\n  - f\n' },

  // 6.1 Backslash escapes
  { section: 'escapes', input: '\\!\\"\\#\\$\\%\\&\\\'\\(\\)\\*\\+\\,\\-\\.\\/\\:\\;\\<\\=\\>\\?\\@\\[\\\\\\]\\^\\_\\`\\{\\|\\}\\~\n' },
  { section: 'escapes', input: '\\\t\\A\\a\\ \\3\\φ\\«\n' },
  { section: 'escapes', input: '\\*not emphasized*\n\\<br/> not a tag\n\\[not a link](/foo)\n\\`not code`\n1\\. not a list\n\\* not a list\n\\# not a heading\n\\[foo]: /url "not a reference"\n\\&ouml; not a character entity\n' },
  { section: 'escapes', input: '\\\\*emphasis*\n' },
  { section: 'escapes', input: 'foo\\\nbar\n' },
  { section: 'escapes', input: '`` \\[\\` ``\n' },
  { section: 'escapes', input: '    \\[\\]\n' },
  { section: 'escapes', input: '~~~\n\\[\\]\n~~~\n' },
  { section: 'escapes', input: '<https://example.com?find=\\*>\n' },
  { section: 'escapes', input: '<a href="/bar\\/)">\n' },
  { section: 'escapes', input: '[foo](/bar\\* "ti\\*tle")\n' },
  { section: 'escapes', input: '[foo]\n\n[foo]: /bar\\* "ti\\*tle"\n' },
  { section: 'escapes', input: '``` foo\\+bar\nfoo\n```\n' },

  // 6.2 Entity and numeric character references
  { section: 'entities', input: '&nbsp; &amp; &copy; &AElig; &Dcaron;\n&frac34; &HilbertSpace; &DifferentialD;\n&ClockwiseContourIntegral; &ngE;\n' },
  { section: 'entities', input: '&#35; &#1234; &#992; &#0;\n' },
  { section: 'entities', input: '&#X22; &#XD06; &#xcab;\n' },
  { section: 'entities', input: '&nbsp &x; &#; &#x;\n&#87654321;\n&#abcdef0;\n&ThisIsNotDefined; &hi?;\n' },
  { section: 'entities', input: '&copy\n' },
  { section: 'entities', input: '&MadeUpEntity;\n' },
  { section: 'entities', input: '<a href="&ouml;&ouml;.html">\n' },
  { section: 'entities', input: '[foo](/f&ouml;&ouml; "f&ouml;&ouml;")\n' },
  { section: 'entities', input: '``` f&ouml;&ouml;\nfoo\n```\n' },
  { section: 'entities', input: '`f&ouml;&ouml;`\n' },
  { section: 'entities', input: '    f&ouml;f&ouml;\n' },
  { section: 'entities', input: '&#42;foo&#42;\n*foo*\n' },
  { section: 'entities', input: '&#42; foo\n\n* foo\n' },
  { section: 'entities', input: 'foo&#10;&#10;bar\n' },
  { section: 'entities', input: '&#9;foo\n' },
  { section: 'entities', input: '[a](url &quot;tit&quot;)\n' },

  // 6.3 Code spans
  { section: 'code spans', input: '`foo`\n' },
  { section: 'code spans', input: '`` foo ` bar ``\n' },
  { section: 'code spans', input: '` `` `\n' },
  { section: 'code spans', input: '`  ``  `\n' },
  { section: 'code spans', input: '` a`\n' },
  { section: 'code spans', input: '` b `\n' },
  { section: 'code spans', input: '` `\n`  `\n' },
  { section: 'code spans', input: '``\nfoo\nbar  \nbaz\n``\n' },
  { section: 'code spans', input: '`foo   bar \nbaz`\n' },
  { section: 'code spans', input: '`foo\\`bar`\n' },
  { section: 'code spans', input: '``foo`bar``\n' },
  { section: 'code spans', input: '` foo `` bar `\n' },
  { section: 'code spans', input: '*foo`*`\n' },
  { section: 'code spans', input: '[not a `link](/foo`)\n' },
  { section: 'code spans', input: '`<a href="`">`\n' },
  { section: 'code spans', input: '<a href="`">`\n' },
  { section: 'code spans', input: '`<https://foo.bar.`baz>`\n' },
  { section: 'code spans', input: '```foo``\n' },
  { section: 'code spans', input: '`foo\n' },
  { section: 'code spans', input: '`foo``bar``\n' },

  // 6.4 Emphasis and strong emphasis
  { section: 'emphasis', input: '*foo bar*\n' },
  { section: 'emphasis', input: 'a * foo bar*\n' },
  { section: 'emphasis', input: 'a*"foo"*\n' },
  { section: 'emphasis', input: '* a *\n' },
  { section: 'emphasis', input: 'foo*bar*\n\n5*6*78\n' },
  { section: 'emphasis', input: '_foo bar_\n' },
  { section: 'emphasis', input: '_ foo bar_\n' },
  { section: 'emphasis', input: 'a_"foo"_\n' },
  { section: 'emphasis', input: 'foo_bar_\n\n5_6_78\n' },
  { section: 'emphasis', input: 'пристаням_стремятся_\n' },
  { section: 'emphasis', input: 'aa_"bb"_cc\n' },
  { section: 'emphasis', input: 'foo-_(bar)_\n' },
  { section: 'emphasis', input: '_foo*\n' },
  { section: 'emphasis', input: '*foo bar *\n' },
  { section: 'emphasis', input: '*foo bar\n*\n' },
  { section: 'emphasis', input: '*(*foo)\n' },
  { section: 'emphasis', input: '*(*foo*)*\n' },
  { section: 'emphasis', input: '**foo bar**\n' },
  { section: 'emphasis', input: '** foo bar**\n' },
  { section: 'emphasis', input: 'a**"foo"**\n' },
  { section: 'emphasis', input: 'foo**bar**\n' },
  { section: 'emphasis', input: '__foo bar__\n' },
  { section: 'emphasis', input: '__ foo bar__\n' },
  { section: 'emphasis', input: '__\nfoo bar__\n' },
  { section: 'emphasis', input: 'foo, __bar__, baz\n' },
  { section: 'emphasis', input: 'foo-__(bar)__\n' },
  { section: 'emphasis', input: '**foo bar **\n' },
  { section: 'emphasis', input: '**(**foo)\n' },
  { section: 'emphasis', input: '*(**foo**)*\n' },
  { section: 'emphasis', input: '**Gomphocarpus (*Gomphocarpus physocarpus*, syn.\n*Asclepias physocarpa*)**\n' },
  { section: 'emphasis', input: '**foo "*bar*" foo**\n' },
  { section: 'emphasis', input: '**foo**bar\n' },
  { section: 'emphasis', input: '*foo [bar](/url)*\n' },
  { section: 'emphasis', input: '*foo\nbar*\n' },
  { section: 'emphasis', input: '_foo __bar__ baz_\n' },
  { section: 'emphasis', input: '__foo_ bar_\n' },
  { section: 'emphasis', input: '*foo **bar** baz*\n' },
  { section: 'emphasis', input: '*foo**bar**baz*\n' },
  { section: 'emphasis', input: '*foo**bar*\n' },
  { section: 'emphasis', input: '***foo** bar*\n' },
  { section: 'emphasis', input: '*foo **bar***\n' },
  { section: 'emphasis', input: '*foo**bar***\n' },
  { section: 'emphasis', input: 'foo***bar***baz\n' },
  { section: 'emphasis', input: 'foo******bar*********baz\n' },
  { section: 'emphasis', input: '*foo **bar *baz* bim** bop*\n' },
  { section: 'emphasis', input: '*foo [*bar*](/url)*\n' },
  { section: 'emphasis', input: '** is not an empty emphasis\n\n**** is not an empty strong emphasis\n' },
  { section: 'emphasis', input: '**foo [bar](/url)**\n' },
  { section: 'emphasis', input: '__foo __bar__ baz__\n' },
  { section: 'emphasis', input: '****foo**bar****\n' },
  { section: 'emphasis', input: '*a `*`*\n\n_a `_`_\n\n**a<https://foo.bar/?q=**>\n\n__a<https://foo.bar/?q=__>\n' },

  // 6.5 Links
  { section: 'links', input: '[link](/uri "title")\n' },
  { section: 'links', input: '[link](/uri)\n' },
  { section: 'links', input: '[](./target.md)\n' },
  { section: 'links', input: '[link]()\n\n[link](<>)\n' },
  { section: 'links', input: '[]()\n' },
  { section: 'links', input: '[link](/my uri)\n\n[link](</my uri>)\n' },
  { section: 'links', input: '[link](\\(foo\\))\n' },
  { section: 'links', input: '[link](foo\\(and\\(bar\\))\n' },
  { section: 'links', input: '[link](<foo(and(bar)>)\n' },
  { section: 'links', input: '[link](foo\\)\\:)\n' },
  { section: 'links', input: '[link](#fragment)\n\n[link](https://example.com#fragment)\n\n[link](https://example.com?foo=3#frag)\n' },
  { section: 'links', input: '[link](foo\\bar)\n' },
  { section: 'links', input: '[link](foo%20b&auml;)\n' },
  { section: 'links', input: '[link]("title")\n' },
  { section: 'links', input: '[link](/url "title")\n[link](/url \'title\')\n[link](/url (title))\n' },
  { section: 'links', input: '[link](/url "title \\"&quot;")\n' },
  { section: 'links', input: '[link](/url\u00a0"title")\n' },
  { section: 'links', input: '[link] bar](/uri)\n\n[link [bar](/uri)\n\n[link \\[bar](/uri)\n' },
  { section: 'links', input: '[link *foo **bar** `#`*](/uri)\n' },
  { section: 'links', input: '[![moon](moon.jpg)](/uri)\n' },
  { section: 'links', input: '[foo *bar](baz*)\n' },
  { section: 'links', input: '*foo [bar* baz]\n' },
  { section: 'links', input: '[foo <bar attr="](baz)">\n' },
  { section: 'links', input: '[foo`](/uri)`\n' },
  { section: 'links', input: '[foo<https://bar.example.com>](/uri)\n' },
  { section: 'links', input: '[foo][bar]\n\n[bar]: /url "title"\n' },
  { section: 'links', input: '[link [foo [bar]]][ref]\n\n[ref]: /uri\n' },
  { section: 'links', input: '[link \\[bar][ref]\n\n[ref]: /uri\n' },
  { section: 'links', input: '[link *foo **bar** `#`*][ref]\n\n[ref]: /uri\n' },
  { section: 'links', input: '[![moon](moon.jpg)][ref]\n\n[ref]: /uri\n' },
  { section: 'links', input: '[foo [bar](/uri)][ref]\n\n[ref]: /uri\n' },
  { section: 'links', input: '[BAR][foo]\n\n[FOO]: /url "title"\n' },
  { section: 'links', input: '[ẽ]\n\n[Ẽ]: /url\n' },
  { section: 'links', input: '[Толпой][Толпой] is a Russian word.\n\n[ТОЛПОЙ]: /url\n' },
  { section: 'links', input: '[foo\n  bar]: /url\n\n[foo bar]\n' },
  { section: 'links', input: '[foo] []\n\n[foo]: /url "title"\n' },
  { section: 'links', input: '[foo][]\n\n[foo]: /url "title"\n' },
  { section: 'links', input: '[*foo* bar][]\n\n[*foo* bar]: /url "title"\n' },
  { section: 'links', input: '[foo][ref[]\n\n[ref[]: /uri\n' },
  { section: 'links', input: '[foo]\n\n[foo]: /url "title"\n' },
  { section: 'links', input: '[*foo* bar]\n\n[*foo* bar]: /url "title"\n' },
  { section: 'links', input: '[[*foo* bar]]\n\n[*foo* bar]: /url "title"\n' },
  { section: 'links', input: '[foo] bar\n\n[foo]: /url\n' },
  { section: 'links', input: '\\[foo]\n\n[foo]: /url "title"\n' },
  { section: 'links', input: '[foo*]: /url\n\n*[foo*]\n' },
  { section: 'links', input: '[foo][bar]\n\n[foo]: /url1\n[bar]: /url2\n' },
  { section: 'links', input: '[foo][]\n\n[foo]: /url1\n' },
  { section: 'links', input: '[foo]()\n\n[foo]: /url1\n' },
  { section: 'links', input: '[foo](not a link)\n\n[foo]: /url1\n' },
  { section: 'links', input: '[foo][bar][baz]\n\n[baz]: /url\n' },
  { section: 'links', input: '[foo][bar][baz]\n\n[baz]: /url1\n[bar]: /url2\n' },

  // 6.6 Images
  { section: 'images', input: '![foo](/url "title")\n' },
  { section: 'images', input: '![foo *bar*]\n\n[foo *bar*]: train.jpg "train & tracks"\n' },
  { section: 'images', input: '![foo ![bar](/url)](/url2)\n' },
  { section: 'images', input: '![foo [bar](/url)](/url2)\n' },
  { section: 'images', input: '![foo][bar]\n\n[bar]: /url\n' },
  { section: 'images', input: 'My ![foo bar](/path/to/train.jpg  "title"   )\n' },
  { section: 'images', input: '![foo](<url>)\n' },
  { section: 'images', input: '![](/url)\n' },
  { section: 'images', input: '![foo]\n\n[foo]: /url "title"\n' },
  { section: 'images', input: '!\\[foo]\n\n[foo]: /url "title"\n' },
  { section: 'images', input: '\\![foo]\n\n[foo]: /url "title"\n' },

  // 6.7 Autolinks
  { section: 'autolinks', input: '<http://foo.bar.baz>\n' },
  { section: 'autolinks', input: '<https://foo.bar.baz/test?q=hello&id=22&boolean>\n' },
  { section: 'autolinks', input: '<irc://foo.bar:2233/baz>\n' },
  { section: 'autolinks', input: '<MAILTO:FOO@BAR.BAZ>\n' },
  { section: 'autolinks', input: '<a+b+c:d>\n' },
  { section: 'autolinks', input: '<made-up-scheme://foo,bar>\n' },
  { section: 'autolinks', input: '<localhost:5001/foo>\n' },
  { section: 'autolinks', input: '<https://foo.bar/baz bim>\n' },
  { section: 'autolinks', input: '<https://example.com/\\[\\>\n' },
  { section: 'autolinks', input: '<foo@bar.example.com>\n' },
  { section: 'autolinks', input: '<foo+special@Bar.baz-bar0.com>\n' },
  { section: 'autolinks', input: '<>\n\n< https://foo.bar >\n\n<m:abc>\n\n<foo.bar.baz>\n\nhttps://example.com\n\nfoo@bar.example.com\n' },

  // 6.8 Raw HTML
  { section: 'raw html', input: '<a><bab><c2c>\n' },
  { section: 'raw html', input: '<a/><b2/>\n' },
  { section: 'raw html', input: '<a  /><b2\ndata="foo" >\n' },
  { section: 'raw html', input: '<a foo="bar" bam = \'baz <em>"</em>\'\n_boolean zoop:33=zoop:33 />\n' },
  { section: 'raw html', input: 'foo <responsive-image src="foo.jpg" />\n' },
  { section: 'raw html', input: '<33> <__>\n\n<a h*#ref="hi">\n\n<a href="hi\'> <a href=hi\'>\n' },
  { section: 'raw html', input: '< a><\nfoo><bar/ >\n<foo bar=baz\nbim!bop />\n' },
  { section: 'raw html', input: '</a></foo >\n\n</a href="foo">\n' },
  { section: 'raw html', input: 'foo <!-- this is a --\ncomment - with hyphens -->\n' },
  { section: 'raw html', input: 'foo <?php echo $a; ?>\n\nfoo <!ELEMENT br EMPTY>\n\nfoo <![CDATA[>&<]]>\n' },
  { section: 'raw html', input: 'foo <a href="&ouml;">\n\nfoo <a href="\\*">\n\n<a href="\\"">\n' },

  // 6.9 Hard line breaks
  { section: 'hard breaks', input: 'foo  \nbaz\n' },
  { section: 'hard breaks', input: 'foo\\\nbaz\n' },
  { section: 'hard breaks', input: 'foo       \nbaz\n' },
  { section: 'hard breaks', input: 'foo  \n     bar\n\nfoo\\\n     bar\n' },
  { section: 'hard breaks', input: '*foo  \nbar*\n\n*foo\\\nbar*\n' },
  { section: 'hard breaks', input: '`code  \nspan`\n\n`code\\\nspan`\n' },
  { section: 'hard breaks', input: '<a href="foo  \nbar">\n\n<a href="foo\\\nbar">\n' },
  { section: 'hard breaks', input: 'foo\\\n\nfoo  \n\n### foo\\\n\n### foo  \n' },

  // 6.10 Soft line breaks, 6.11 Textual content
  { section: 'soft breaks', input: 'foo\nbaz\n' },
  { section: 'soft breaks', input: 'foo \n baz\n' },
  { section: 'textual content', input: 'hello $.;\'there\n\nFoo χρῆν\n\nMultiple     spaces\n' },

  // Mixed documents, and the shapes a README actually takes
  { section: 'documents', input: '' },
  { section: 'documents', input: '\n' },
  { section: 'documents', input: 'no trailing newline' },
  { section: 'documents', input: '# Title\n\nSome *text* with a [link](https://example.invalid).\n\n- a\n- b\n\n```ts\nconst x: number = 1;\n```\n\n> quote\n\n| a | b |\n| - | - |\n| 1 | 2 |\n' },
  { section: 'documents', input: '一段中文，带有 **强调** 和 `代码`。\n\n第二段。\n' },
  { section: 'documents', input: 'مرحبا **بالعالم** مع [رابط](https://example.invalid).\n' },
  { section: 'documents', input: 'emoji 😀 and surrogate pairs 👨‍👩‍👧 in *text*\n' },
  { section: 'documents', input: 'line one\r\nline two\r\n\r\n# heading\r\n' },
  { section: 'documents', input: '> - a\n>   - b\n>\n> ```\n> code\n> ```\n' },
] as const;
