#!/usr/bin/env node
// MARXY-19: measures ragged-right paragraph setting quality for justif/core and tex-linebreak2 over
// the whole fixture corpus and writes the tables in packages/typeset/RESEARCH.md. A study harness,
// not product code: nothing here is imported by packages/typeset/src.
//
//   node packages/typeset/scripts/measure-rag.mjs            # print the tables
//   node packages/typeset/scripts/measure-rag.mjs --write     # refresh RESEARCH.md
//   node packages/typeset/scripts/measure-rag.mjs --verify    # fail if RESEARCH.md is stale
//   node packages/typeset/scripts/measure-rag.mjs --selftest  # check the metric arithmetic
import { createRequire } from 'node:module';
import { execFileSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { mkdirSync, readFileSync, readdirSync, writeFileSync, existsSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { readFont } from './font-metrics.mjs';
import { INF_BAD, assertOneParagraphSet, badness, buildRaggedItems, commonParagraphs, extractParagraphs, greedyBreakpoints, lineWidths, ragMetrics, selectPool } from './rag-model.mjs';

const root = fileURLToPath(new URL('../../../', import.meta.url));
const research = join(root, 'packages/typeset/RESEARCH.md');
const START = '<!-- rag-table:start (generated by packages/typeset/scripts/measure-rag.mjs; do not edit by hand) -->';
const END = '<!-- rag-table:end -->';

/** Every knob the numbers depend on. Changing one changes the table, so the table names them. */
const CONFIG = {
  measureCh: 68,
  fontPath: 'fonts/literata/Literata[opsz,wght].ttf',
  /** What the BREAKERS are fed: word-glue stretch in em, standing in for TeX's `\rightskip`. 0.6em is
   * three space advances in Literata, which is tex-linebreak2's own default for unjustified text. */
  glueStretchEm: 0.6,
  /** What the METRIC prices against: `\rightskip = 0pt plus 2em`, ragged2e's \RaggedRight tolerance.
   * Held fixed across the sweep so every badness figure in this file is on one scale. */
  badnessStretchEm: 2,
  /** A line is "short" when its shortfall exceeds this fraction of the measure. */
  shortLineFraction: 0.1,
  exHyphenPenalty: 50,
  /** Sensitivity sweep: if the ranking flips across these, the recommendation is not robust. */
  sweep: [0.2, 0.6, 2],
};

/** The fallback engine is deliberately not a repo dependency (ADR-0006): it is fetched, pinned by
 * content hash, and kept out of the tree so `pnpm gate:licences` audits only what marxy ships. */
const FALLBACK = {
  spec: 'tex-linebreak2@0.8.4',
  entry: 'node_modules/tex-linebreak2/dist/lib.js',
  sha256: '90dac2e4d37cf99316ed7f94cd28fed8776944eb828a5aafa26baf639bcb5653',
  dir: join(tmpdir(), 'marxy-rag-vendor'),
};

async function loadEngines() {
  const justif = await import('justif/core');
  const justifVersion = JSON.parse(readFileSync(join(root, 'packages/typeset/node_modules/justif/package.json'), 'utf8')).version;
  return {
    justif: { module: justif, version: justifVersion },
    fallback: loadFallback(),
  };
}

function loadFallback() {
  const entry = join(FALLBACK.dir, FALLBACK.entry);
  if (!existsSync(entry)) {
    mkdirSync(FALLBACK.dir, { recursive: true });
    writeFileSync(join(FALLBACK.dir, 'package.json'), JSON.stringify({ name: 'marxy-rag-vendor', private: true }) + '\n');
    execFileSync('npm', ['install', '--no-save', '--no-audit', '--no-fund', '--loglevel=error', FALLBACK.spec], { cwd: FALLBACK.dir, stdio: 'inherit' });
  }
  const bytes = readFileSync(entry);
  const sha = createHash('sha256').update(bytes).digest('hex');
  if (sha !== FALLBACK.sha256) throw new Error(`${FALLBACK.spec} content hash mismatch: expected ${FALLBACK.sha256}, got ${sha}`);
  return { module: createRequire(join(FALLBACK.dir, 'index.cjs'))('tex-linebreak2'), version: FALLBACK.spec.split('@').pop(), licences: auditFallbackLicences() };
}

/** ADR-0006 for the engine the licence gate cannot see: it is out of tree by design, so the study
 * audits its own copy and refuses to report a measurement made under a copyleft licence. */
function auditFallbackLicences() {
  const permissive = /^(MIT|ISC|BSD-[23]-Clause|Apache-2\.0|0BSD|Unlicense|CC0-1\.0|MPL-2\.0)$/;
  const modules = join(FALLBACK.dir, 'node_modules');
  const found = readdirSync(modules)
    .filter((name) => !name.startsWith('.'))
    .sort()
    .map((name) => ({ name, licence: JSON.parse(readFileSync(join(modules, name, 'package.json'), 'utf8')).license ?? 'UNDECLARED' }));
  const copyleft = found.filter((p) => !permissive.test(p.licence));
  if (copyleft.length) throw new Error(`the fallback engine's dependency tree is not permissive: ${copyleft.map((p) => `${p.name} (${p.licence})`).join(', ')}`);
  return found;
}

/** justif/core over a hand-built stream: classic Knuth–Plass, protrusion and expansion off, so the
 * comparison is of breakers and not of justif's microtypography. */
function justifBreakpoints(module, items, measure, breakOptions) {
  const { ItemType, INF_PENALTY, withSums, breakParagraph, defaultBreakOptions } = module;
  const run = { fontKey: 'literata', space: { width: 0, stretch: 0, shrink: 0 }, hyphenWidth: 0, ratioAtMax: 1, ratioAtMin: 1 };
  const converted = items.map((item) => {
    if (item.kind === 'box')
      return { type: ItemType.Box, width: item.width, run: 0, text: item.text, lp: 0, lpFirst: 0, rp: 0, hangStretch: 0, hangShrink: 0, expStretch: 0, expShrink: 0, trackStretch: 0, trackShrink: 0 };
    if (item.kind === 'glue')
      return { type: ItemType.Glue, width: item.width, stretch: item.stretch, stretchFil: item.fil ? 1 : 0, shrink: item.shrink, run: 0 };
    return { type: ItemType.Penalty, penalty: item.forced ? -INF_PENALTY : item.penalty, width: item.width, flagged: item.flagged, hyphen: false, rp: 0, run: 0 };
  });
  const result = breakParagraph(withSums(converted, [run]), measure, breakOptions ?? { ...defaultBreakOptions });
  return [0, ...result.breakpoints];
}

/** tex-linebreak2's `breakLines` over the identical stream. Its cost knobs are set to TeX's values
 * where it exposes them; the ones it does not expose are its own. */
function fallbackBreakpoints(module, items, measure) {
  const converted = items.map((item) => {
    if (item.kind === 'box') return { type: 'box', width: item.width };
    if (item.kind === 'glue') return { type: 'glue', width: item.width, stretch: item.fil ? module.INFINITE_STRETCH : item.stretch, shrink: item.shrink };
    return { type: 'penalty', width: item.width, cost: item.forced ? module.MIN_COST : item.penalty, flagged: item.flagged };
  });
  return module.breakLines(converted, {
    lineWidth: measure,
    doubleHyphenPenalty: INF_BAD,
    adjacentLooseTightPenalty: INF_BAD,
    preventSingleWordLines: false,
    validateItems: false,
  }).breakpoints;
}

const ENGINES = ['justif/core', 'tex-linebreak2', 'greedy (baseline)'];

function measureCorpus(engines, font, glueStretchEm) {
  const measure = CONFIG.measureCh * font.advanceOf(0x30);
  const opts = { glueStretchEm, badnessStretchEm: CONFIG.badnessStretchEm, exHyphenPenalty: CONFIG.exHyphenPenalty, shortLineFraction: CONFIG.shortLineFraction };
  const corpus = join(root, 'fixtures/corpus');
  const documents = [];
  const pooled = new Map(ENGINES.map((e) => [e, []]));
  const agreement = { paragraphs: 0, enginesAgree: 0, justifMatchesGreedy: 0, optionAudit: 0 };
  for (const file of readdirSync(corpus).sort()) {
    const source = readFileSync(join(corpus, file), 'utf8');
    const paragraphs = file.endsWith('.md') ? extractParagraphs(source).map((text) => buildRaggedItems(text, font, opts)) : [];
    const setting = paragraphs.filter((items) => {
      const widths = lineWidths(items, [0, items.length - 1]);
      return widths[0] > measure; // a paragraph that fits on one line has no rag to measure
    });
    const row = { file, typeset: file.endsWith('.md'), paragraphs: setting.length, engines: {} };
    const chosen = {};
    for (const engine of ENGINES) {
      chosen[engine] = setting.map((items) => breakWith(engine, engines, items, measure));
      const perParagraph = setting.map((items, i) => ({ id: `${file}#${i}`, widths: lineWidths(items, chosen[engine][i]) }));
      pooled.get(engine).push(...perParagraph);
      row.engines[engine] = ragMetrics(perParagraph.map((p) => p.widths), measure, opts);
    }
    for (let i = 0; i < setting.length; i++) {
      agreement.paragraphs++;
      if (String(chosen[ENGINES[0]][i]) === String(chosen[ENGINES[1]][i])) agreement.enginesAgree++;
      if (String(chosen[ENGINES[0]][i]) === String(chosen[ENGINES[2]][i])) agreement.justifMatchesGreedy++;
      agreement.optionAudit += auditJustifOptions(engines.justif.module, setting[i], measure, chosen[ENGINES[0]][i]);
    }
    documents.push(row);
  }
  const pools = Object.fromEntries(ENGINES.map((e) => [e, pooled.get(e)]));
  const common = commonParagraphs(pools, measure);
  const corpusTotals = Object.fromEntries(ENGINES.map((e) => [e, ragMetrics(pooled.get(e).map((p) => p.widths), measure, opts)]));
  /** The ranking row: one paragraph set, so no engine is scored over a pool its own failures thinned.
   * The guard re-derives what each engine was actually scored over and throws if they ever diverge. */
  const scored = Object.fromEntries(ENGINES.map((e) => [e, { ids: common, widths: selectPool(pools[e], common) }]));
  assertOneParagraphSet(Object.fromEntries(ENGINES.map((e) => [e, scored[e].ids])));
  const commonTotals = Object.fromEntries(ENGINES.map((e) => [e, ragMetrics(scored[e].widths, measure, opts)]));
  /** Diagnostic only. Each row drops the paragraphs THAT engine overflowed, so the rows are not
   * comparable with each other; they are here to show how much each engine's own failures flatter it. */
  const fits = (p) => p.widths.every((w) => w <= measure + 1e-9);
  const ownSuccessTotals = Object.fromEntries(ENGINES.map((e) => [e, ragMetrics(pooled.get(e).filter(fits).map((p) => p.widths), measure, opts)]));
  /** How many paragraphs each arrangement pushed past the margin, counting the last line too: the
   * number conclusion 4 rests on, and the reason the common set is smaller than the corpus. */
  const overflowed = Object.fromEntries(ENGINES.map((e) => [e, pooled.get(e).filter((p) => !fits(p)).length]));
  return {
    measure,
    glueStretchEm,
    chWidth: font.advanceOf(0x30),
    documents,
    corpusTotals,
    commonTotals,
    ownSuccessTotals,
    commonParagraphs: common.length,
    overflowed,
    totalParagraphs: pooled.get(ENGINES[0]).length,
    agreement,
  };
}

/**
 * Justif is driven at its own defaults (tolerance 200, `emergencyStretch: 'auto'`) while
 * tex-linebreak2 is driven at its own, which is an asymmetry a reader is entitled to see priced.
 * Returns 1 when the paragraph's breaks survive removing both of those justif-only escapes.
 */
function auditJustifOptions(module, items, measure, baseline) {
  const { defaultBreakOptions } = module;
  const variants = [
    { ...defaultBreakOptions, emergencyStretch: 0 },
    { ...defaultBreakOptions, tolerance: INF_BAD, pretolerance: INF_BAD },
  ];
  return variants.every((opts) => String(justifBreakpoints(module, items, measure, opts)) === String(baseline)) ? 1 : 0;
}

function breakWith(engine, engines, items, measure) {
  if (engine === 'justif/core') return justifBreakpoints(engines.justif.module, items, measure);
  if (engine === 'tex-linebreak2') return fallbackBreakpoints(engines.fallback.module, items, measure);
  return greedyBreakpoints(items, measure);
}

const n4 = (v) => (v === null ? '—' : v.toFixed(4));
const n1 = (v) => (v === null ? '—' : v.toFixed(1));
const n0 = (v) => (v === null ? '—' : String(Math.round(v)));

function renderTables(main, sweep, engines, font) {
  const ch = (em) => (em === null ? '—' : (em / main.chWidth).toFixed(1));
  const out = [];
  out.push(`Measure **${CONFIG.measureCh}ch = ${main.measure.toFixed(3)} em** in \`${CONFIG.fontPath}\` (default instance ${Object.entries(font.axes).map(([k, v]) => `${k} ${v}`).join(', ')}).`);
  out.push(`Engines: **justif/core ${engines.justif.version}** (MIT), **tex-linebreak2 ${engines.fallback.version}** (MIT), and a first-fit greedy baseline standing in for the engine's own wrapping.`);
  out.push(`Both breakers are fed the same stream: word glue of ${main.glueStretchEm}em stretch and no shrink. Badness is priced against \`\\rightskip = 0pt plus ${CONFIG.badnessStretchEm}em\`; a line is *short* when its shortfall exceeds ${CONFIG.shortLineFraction * 100}% of the measure (${(CONFIG.shortLineFraction * CONFIG.measureCh).toFixed(1)}ch). Shortfalls are in ch. Every metric excludes each paragraph's last line, which is short by construction.`);
  out.push('');
  out.push('| Document | Paras | Engine | Lines | CV | Short lines | Mean shortfall | p95 shortfall | Worst badness | Overfull |');
  out.push('| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |');
  const row = (label, paras, engine, m, bold = false) => {
    const b = bold ? '**' : '';
    out.push(`| ${label} | ${paras} | ${b}${engine}${b} | ${b}${m.lines}${b} | ${b}${n4(m.cv)}${b} | ${b}${n0(m.shortLines)} (${n1(m.shortLineRate)}%)${b} | ${b}${ch(m.meanShortfall)}${b} | ${b}${ch(m.p95Shortfall)}${b} | ${b}${n0(m.worstBadness)}${b} | ${b}${m.overfull}${b} |`);
  };
  for (const doc of main.documents) {
    if (!doc.typeset || doc.paragraphs === 0) {
      out.push(`| \`${doc.file}\` | 0 | — | — | — | — | — | — | — | — |`);
      continue;
    }
    for (const engine of ENGINES) row(engine === ENGINES[0] ? `\`${doc.file}\`` : '', engine === ENGINES[0] ? doc.paragraphs : '', engine, doc.engines[engine]);
  }
  for (const engine of ENGINES) row('**corpus, every paragraph**', '', engine, main.corpusTotals[engine], true);
  for (const engine of ENGINES) row(`**corpus, the ${main.commonParagraphs} paragraphs all three set inside the measure** ← the ranking`, '', engine, main.commonTotals[engine], true);
  for (const engine of ENGINES) row('*diagnostic: each engine over only its own successes — rows NOT comparable*', '', engine, main.ownSuccessTotals[engine]);
  out.push('');
  out.push(`The third block is the one to read. Both other blocks pool over sets that differ between rows — the first because an overfull line still scores, the last because each row drops the paragraphs *that* engine overflowed, which removes an engine's own failures from its own score. The last block is printed only to show the size of that bias; ${main.totalParagraphs - main.commonParagraphs} of ${main.totalParagraphs} paragraphs are outside the common set.`);
  out.push('');
  out.push(`Paragraphs pushed past the margin, last line included: ${ENGINES.map((e) => `**${e} ${main.overflowed[e]}**`).join(', ')}, out of ${main.totalParagraphs}.`);
  out.push('');
  out.push(`Of the ${main.agreement.paragraphs} paragraphs long enough to break, the two Knuth–Plass engines chose **identical** breakpoints in **${main.agreement.enginesAgree}** and justif/core matched the greedy baseline in **${main.agreement.justifMatchesGreedy}**.`);
  out.push('');
  out.push(`justif/core is driven at its own defaults (tolerance 200, \`emergencyStretch: 'auto'\`) and tex-linebreak2 at its own, so justif has two escapes its rival lacks. Removing them changes nothing here: forcing \`emergencyStretch: 0\`, and separately opening \`tolerance\` to ${INF_BAD}, reproduce justif's breakpoints in **${main.agreement.optionAudit} of ${main.agreement.paragraphs}** paragraphs.`);
  out.push('');
  out.push(`Licences of the out-of-tree fallback and everything under it, read from the fetched copy: ${engines.fallback.licences.map((p) => `${p.name} ${p.licence}`).join(', ')}. The harness refuses to report a measurement if any of them is not permissive.`);
  out.push('');
  out.push('### Sensitivity to the glue stretch the breakers are fed');
  out.push('');
  out.push('Each row is pooled over the common set recomputed at that stretch, with the badness denominator held at 2em throughout. The glue stretch is the breakers’ own rag tolerance and therefore the one parameter that could invent the result: the recommendation stands only if the ranking holds across the sweep.');
  out.push('');
  out.push('| Glue stretch | Engine | Lines | CV | Short lines | Mean shortfall | Worst badness |');
  out.push('| --- | --- | --- | --- | --- | --- | --- |');
  for (const run of sweep) {
    for (const engine of ENGINES) {
      const m = run.commonTotals[engine];
      out.push(`| ${engine === ENGINES[0] ? `${run.glueStretchEm}em` : ''} | ${engine} | ${m.lines} | ${n4(m.cv)} | ${n1(m.shortLineRate)}% | ${ch(m.meanShortfall)} | ${n0(m.worstBadness)} |`);
    }
  }
  return out.join('\n');
}

function selftest() {
  const checks = [];
  const check = (name, condition, detail = '') => checks.push({ name, ok: !!condition, detail });

  // TeX's own published badness values (TeXbook: full stretch = 100, half = 12).
  check('badness(1,1) = 100', badness(1, 1) === 100, String(badness(1, 1)));
  check('badness(0.5,1) = 12', badness(0.5, 1) === 12, String(badness(0.5, 1)));
  check('badness(0,1) = 0', badness(0, 1) === 0);
  check('badness saturates at INF_BAD', badness(100, 1) === INF_BAD);
  check('rigid glue is infinitely bad', badness(1, 0) === INF_BAD);

  // Metric arithmetic against hand-computed values.
  const opts = { badnessStretchEm: 1, shortLineFraction: 0.2 };
  const m = ragMetrics([[8, 10, 12, 3]], 12, opts);
  check('cv over non-final lines only', Math.abs(m.cv - Math.sqrt(((8 - 10) ** 2 + 0 + (12 - 10) ** 2) / 3) / 10) < 1e-12, String(m.cv));
  check('short-line count uses the shortfall threshold', m.shortLines === 1, `${m.shortLines}`);
  check('worst badness is the worst non-final line', m.worstBadness === badness(4, 1), `${m.worstBadness}`);
  check('paragraph last lines are counted, never scored', m.lines === 3 && m.lastLines === 1);
  check('single-line paragraphs contribute nothing', ragMetrics([[7]], 12, opts).lines === 0);
  const even = ragMetrics([[12, 12, 12, 5]], 12, opts);
  check('a perfect rectangle scores cv 0 and badness 0', even.cv === 0 && even.worstBadness === 0);

  // The metric must be able to fail: a worse rag must score worse on all three numbers.
  const good = ragMetrics([[11, 12, 11, 4]], 12, opts);
  const bad = ragMetrics([[4, 12, 6, 4]], 12, opts);
  check('a ragged set scores worse than an even one', bad.cv > good.cv && bad.shortLines > good.shortLines && bad.worstBadness > good.worstBadness);

  // The defect review round 1 found: a "comparison" row pooled over each engine's own successes.
  // Engine A overflows p1, engine B overflows p2, and the paragraph both set is p0 plus p3.
  const pools = {
    a: [
      { id: 'p0', widths: [12, 11, 4] },
      { id: 'p1', widths: [14, 11, 4] },
      { id: 'p2', widths: [12, 12, 4] },
      { id: 'p3', widths: [11, 12, 4] },
    ],
    b: [
      { id: 'p0', widths: [12, 11, 4] },
      { id: 'p1', widths: [12, 11, 4] },
      { id: 'p2', widths: [13, 12, 4] },
      { id: 'p3', widths: [11, 12, 4] },
    ],
  };
  const common = commonParagraphs(pools, 12);
  check('the common set drops a paragraph EITHER engine overflowed', String(common) === 'p0,p3', String(common));
  check('the common set scores both engines over the same paragraphs', selectPool(pools.a, common).length === selectPool(pools.b, common).length);
  const ownSuccesses = (pool) => pool.filter((p) => p.widths.every((w) => w <= 12)).map((p) => p.id);
  check('per-engine pools really do differ, which is why they cannot be ranked', String(ownSuccesses(pools.a)) !== String(ownSuccesses(pools.b)), `${ownSuccesses(pools.a)} vs ${ownSuccesses(pools.b)}`);
  check('the guard accepts one shared paragraph set', String(assertOneParagraphSet({ a: common, b: common })) === 'p0,p3');
  let refused = '';
  try {
    assertOneParagraphSet({ a: ownSuccesses(pools.a), b: ownSuccesses(pools.b) });
  } catch (e) {
    refused = e.message;
  }
  check('the guard refuses per-engine paragraph sets, which is the defect that returned round 1', refused.startsWith('refusing to rank over different paragraph sets'), refused || 'no error thrown');
  check('the per-engine pool is measurably more flattering than the common one', ragMetrics(selectPool(pools.a, ownSuccesses(pools.a)), 12, opts).cv < ragMetrics(selectPool(pools.a, common), 12, opts).cv);

  // Paragraph extraction.
  const md = ['# Heading', '', 'One two', 'three four.', '', '```js', 'const x = 1;', '```', '', '- item **one**', '- item `two`', '', '| a | b |', '| - | - |', '', '> quoted text'].join('\n');
  const paragraphs = extractParagraphs(md);
  check('prose paragraphs are joined across source lines', paragraphs[0] === 'One two three four.', JSON.stringify(paragraphs[0]));
  check('code fences, headings and tables are dropped', !paragraphs.some((p) => p.includes('const x') || p.includes('Heading') || p.includes('| a')), JSON.stringify(paragraphs));
  check('list items are separate paragraphs with markup removed', paragraphs.includes('item one') && paragraphs.includes('item two'), JSON.stringify(paragraphs));
  check('blockquote markers are stripped', paragraphs.includes('quoted text'), JSON.stringify(paragraphs));

  // Greedy breaking and width accounting, on a stream with unit boxes and unit glue.
  const font = { advanceOf: () => 1, widthOf: (t) => t.length };
  const items = buildRaggedItems('aa bb cc dd ee ff', font, { glueStretchEm: 1, exHyphenPenalty: 50 });
  const greedy = greedyBreakpoints(items, 8);
  const widths = lineWidths(items, greedy);
  check('greedy fills each line as far as it fits', widths.slice(0, -1).every((w) => w <= 8 && w > 8 - 3), JSON.stringify(widths));
  // The bug this catches flattered the baseline: an unchecked tail let greedy run past the measure,
  // which both saves a line and evens the rag, so K–P looked worse than engine wrapping.
  const tail = buildRaggedItems('aa bb cc dd ee ff gg', font, { glueStretchEm: 1, exHyphenPenalty: 50 });
  check('greedy never overflows the measure when a legal break exists', lineWidths(tail, greedyBreakpoints(tail, 8)).every((w) => w <= 8), JSON.stringify(lineWidths(tail, greedyBreakpoints(tail, 8))));
  const unbreakable = buildRaggedItems('aaaaaaaaaaaa', font, { glueStretchEm: 1, exHyphenPenalty: 50 });
  check('greedy still returns one line when nothing can break', lineWidths(unbreakable, greedyBreakpoints(unbreakable, 8)).length === 1);
  check('line widths never count the glue at a break', widths.every((w) => Number.isInteger(w)), JSON.stringify(widths));
  const single = lineWidths(items, [0, items.length - 1]);
  check('an unbroken paragraph measures the whole natural width', single.length === 1 && single[0] === 6 * 2 + 5, JSON.stringify(single));

  // The font reader, against values a hex dump of the file confirms.
  const literata = readFont(join(root, CONFIG.fontPath));
  check('font units per em', literata.unitsPerEm === 1000, String(literata.unitsPerEm));
  check('default instance is wght 400', literata.axes.wght === 400, JSON.stringify(literata.axes));
  check('advance of "0" defines the ch unit', Math.abs(literata.advanceOf(0x30) - 0.578) < 1e-9, String(literata.advanceOf(0x30)));
  check('string width is the sum of advances', Math.abs(literata.widthOf('00') - 2 * literata.advanceOf(0x30)) < 1e-12);

  const failed = checks.filter((c) => !c.ok);
  for (const c of checks) console.log(`${c.ok ? 'ok  ' : 'FAIL'} ${c.name}${c.ok ? '' : ` — ${c.detail}`}`);
  console.log(`${checks.length - failed.length}/${checks.length} selftest checks passed`);
  return failed.length === 0;
}

function assertSourceUntouched() {
  const problems = [];
  try {
    const diff = execFileSync('git', ['diff', '--name-only', 'origin/main...HEAD', '--', 'packages/typeset/src'], { cwd: root, encoding: 'utf8' }).trim();
    if (diff) problems.push(`committed changes under packages/typeset/src:\n${diff}`);
  } catch (e) {
    problems.push(`could not diff against origin/main: ${e.message.split('\n')[0]}`);
  }
  const dirty = execFileSync('git', ['status', '--porcelain', '--', 'packages/typeset/src'], { cwd: root, encoding: 'utf8' }).trim();
  if (dirty) problems.push(`uncommitted changes under packages/typeset/src:\n${dirty}`);
  return problems;
}

const args = process.argv.slice(2);
if (args.includes('--selftest')) process.exit(selftest() ? 0 : 1);

const font = readFont(join(root, CONFIG.fontPath));
const engines = await loadEngines();
const main = measureCorpus(engines, font, CONFIG.glueStretchEm);
const sweep = CONFIG.sweep.map((n) => (n === CONFIG.glueStretchEm ? main : measureCorpus(engines, font, n)));

if (args.includes('--json')) {
  console.log(JSON.stringify({ config: CONFIG, engines: { justif: engines.justif.version, texLinebreak2: engines.fallback.version }, main, sweep }, null, 2));
  process.exit(0);
}

const block = `${START}\n\n${renderTables(main, sweep, engines, font)}\n\n${END}`;

if (args.includes('--write')) {
  const doc = readFileSync(research, 'utf8');
  const start = doc.indexOf(START);
  const end = doc.indexOf(END);
  if (start === -1 || end === -1) throw new Error(`RESEARCH.md is missing the ${START} / ${END} markers`);
  writeFileSync(research, doc.slice(0, start) + block + doc.slice(end + END.length));
  console.log(`wrote the generated block into ${research}`);
  process.exit(0);
}

if (args.includes('--verify')) {
  const doc = readFileSync(research, 'utf8');
  const problems = assertSourceUntouched();
  if (!doc.includes(block)) problems.push('RESEARCH.md does not contain the freshly measured table; re-run with --write');
  if (!selftest()) problems.push('the metric selftest failed');
  if (problems.length) {
    console.error(`rag study verification failed:\n - ${problems.join('\n - ')}`);
    process.exit(1);
  }
  console.log(`rag study verified: RESEARCH.md matches a fresh measurement of ${main.documents.length} corpus documents, and packages/typeset/src is unchanged`);
  process.exit(0);
}

console.log(block);
