// The fleet's report: status.md, the "Needs you" list, and a quiet log (ADR-0034).
//
// status.md answers, for every story that is not done, who owns it now and what happens next, and
// lists what only a person can do at the top. It is generated from the board every cycle and written
// to the fleet store and to the main checkout's gitignored orchestration/status.md; nothing reads it
// back. The loop log gets one heartbeat line per cycle plus only the lines that changed since the last
// one: an unchanged wait is not news (the old log printed the same dozen lines every two minutes).
import { existsSync, statSync } from 'node:fs';
import { join } from 'node:path';
import { fleetPath, repoHome, readJsonOr, writeJsonAtomic, writeTextAtomic, runFile } from './store.mjs';
import { STATES } from './machine.mjs';

const hhmm = iso => (iso ? String(iso).slice(11, 16) + 'Z' : '?');
const ago = (iso, nowMs) => {
  const min = Math.round((nowMs - Date.parse(iso)) / 60_000);
  if (!Number.isFinite(min)) return '?';
  return min < 90 ? `${min} min` : min < 48 * 60 ? `${Math.round(min / 60)} h` : `${Math.round(min / 1440)} d`;
};

/** Everything a person must do, most urgent first. Pure. */
export function needsYou({ board, attention = [], nowMs }) {
  const items = [...attention];
  for (const [key, rec] of Object.entries(board.stories)) {
    if (rec.status === 'blocked') items.push({ key, why: `blocked ${ago(rec.blockedAt ?? rec.since, nowMs)}: ${rec.parkedReason ?? rec.why ?? 'no reason recorded'} — \`node orchestration/fleet.mjs unpark ${key}\` when it can move` });
    if (rec.status === 'escalate') items.push({ key, why: `escalated ${ago(rec.blockedAt ?? rec.since, nowMs)}: ${rec.why ?? ''} — the planner splits it, or \`node orchestration/fleet.mjs retry ${key}\`` });
  }
  for (const r of board.rejected.slice(-5)) {
    if (nowMs - Date.parse(r.at) < 3_600_000) items.push({ key: r.key, why: `a command was refused: ${r.why} (${r.event})`, quiet: true });
  }
  const rank = i => (i.gate ? 0 : i.quiet ? 2 : 1);
  const seen = new Set();
  return items
    .sort((a, b) => rank(a) - rank(b))
    .filter(i => { const k = `${i.key}|${i.why}`; if (seen.has(k)) return false; seen.add(k); return true; });
}

/** One line per story that is in flight: owner, what it is doing, and when that ends. Pure. */
export function inFlight({ board, nowMs, outputOf = () => null }) {
  const out = [];
  for (const [key, rec] of Object.entries(board.stories)) {
    if (rec.status === 'in_progress') {
      if (rec.run) {
        const run = board.runs[rec.run] ?? {};
        const o = outputOf(rec.run);
        out.push(`**${key}** in progress — ${run.role ?? 'implement'} run on ${run.model ?? rec.model ?? '?'} (attempt ${rec.attempts}), started ${hhmm(run.started)}, ends by ${hhmm(run.deadline)}${o ? `, ${Math.round(o.bytes / 1024)} KB of output, last ${o.lastMs ? ago(new Date(o.lastMs).toISOString(), nowMs) : '?'} ago` : ''}`);
      } else if (rec.claim) {
        out.push(`**${key}** in progress — claimed by ${rec.claim.by} until ${hhmm(rec.claim.until)}${rec.claim.note ? ` (${rec.claim.note})` : ''}`);
      }
    } else if (rec.status === 'in_review') {
      const run = rec.run ? board.runs[rec.run] : null;
      const doing = run ? `${run.role} run until ${hhmm(run.deadline)}` : rec.hold ? `${rec.hold.class}: ${rec.hold.reason} (${ago(rec.hold.since, nowMs)})` : 'next cycle decides';
      out.push(`**${key}** in review, PR #${rec.pr} — ${doing}`);
    }
  }
  return out.sort();
}

/** status.md. Pure. */
export function renderStatus(r, { nowMs = Date.parse(r.at), outputOf } = {}) {
  const { board, attention, lines, ready } = r;
  const by = {};
  for (const [k, rec] of Object.entries(board.stories)) (by[rec.status] ??= []).push(k);
  const counts = Object.keys(STATES).map(s => `${s} ${by[s]?.length ?? 0}`).join(' · ');
  const needs = needsYou({ board, attention, nowMs });
  const flight = inFlight({ board, nowMs, outputOf });
  const waits = Object.entries(ready?.waits ?? {});
  const grouped = {};
  for (const [k, why] of waits) (grouped[why] ??= []).push(k);
  return `# Fleet status — ${r.at}${r.dry ? ' (dry run)' : ''}

Generated by \`orchestration/cycle.mjs\` every cycle; compute **${r.compute}**. ${counts}.
Planner: ${board.planner?.run ? `running since ${hhmm(board.planner.started)}` : board.planner?.lastEnded ? `last ran ${ago(board.planner.lastEnded, nowMs)} ago (${board.planner.lastOutcome})` : 'no run recorded'}.

## Needs you (${needs.length})

${needs.length ? needs.map(i => `- ${i.gate ? '**gate** ' : ''}**${i.key}** — ${i.why}`).join('\n') : '- nothing'}

## In flight (${flight.length})

${flight.length ? flight.map(l => `- ${l}`).join('\n') : '- nothing'}

## Ready to start (${ready?.ready?.length ?? 0})

${ready?.ready?.length ? ready.ready.map(x => `- **${x.key}** ${x.summary ?? ''}`).join('\n') : '- nothing this cycle'}

## Waiting (${waits.length})

${waits.length ? Object.entries(grouped).map(([why, keys]) => `- ${keys.join(', ')} — ${why}`).join('\n') : '- nothing'}

## This cycle

${lines.length ? lines.map(l => `- ${l}`).join('\n') : '- no changes'}

## Done (${by.done?.length ?? 0})

${(by.done ?? []).join(', ') || '—'}
`;
}

/** What a run's output looks like right now: size and last write. */
function outputOf(id) {
  const p = runFile(id, 'out.log');
  if (!existsSync(p)) return null;
  const { size, mtimeMs } = statSync(p);
  return { bytes: size, lastMs: mtimeMs };
}

/** The lines worth printing this cycle: a heartbeat, then only what differs from the last cycle. */
export function changedLines(prev, r, needs) {
  const before = new Set([...(prev?.lines ?? []), ...(prev?.needs ?? [])]);
  const now = [...r.lines, ...needs.map(n => `needs you: ${n.key} — ${n.why}`)];
  const flight = Object.values(r.board.stories).filter(s => s.status === 'in_progress' || s.status === 'in_review').length;
  const heartbeat = `── cycle ${r.at.slice(0, 16)}Z: ${flight} in flight, ${needs.length} need you, ${r.ready?.ready?.length ?? 0} ready`;
  return { heartbeat, fresh: now.filter(l => !before.has(l)), all: now };
}

/** Write status.md (store and main checkout) and print what changed. Returns the report. */
export function writeReport(r, { print = console.log } = {}) {
  const nowMs = Date.parse(r.at);
  const text = renderStatus(r, { nowMs, outputOf });
  if (r.dry) {
    // A dry run changes nothing anywhere: the status goes to the terminal, not to status.md.
    print(text);
    return { ...r, needs: needsYou({ board: r.board, attention: r.attention, nowMs }), text };
  }
  writeTextAtomic(fleetPath('status.md'), text);
  const mirror = join(repoHome(), 'orchestration');
  if (existsSync(mirror)) writeTextAtomic(join(mirror, 'status.md'), text);
  const statePath = fleetPath('report.json');
  const prev = readJsonOr(statePath, null);
  const needs = needsYou({ board: r.board, attention: r.attention, nowMs });
  const { heartbeat, fresh, all } = changedLines(prev, r, needs);
  print(heartbeat);
  for (const l of fresh) print(`  ${l}`);
  if (!r.dry) writeJsonAtomic(statePath, { at: r.at, lines: r.lines, needs: all.filter(l => l.startsWith('needs you: ')) });
  return { ...r, needs, text };
}
